### ISSUE TITLE
[Question]is there easy way to get the pre ptr?

### ISSUE THREAD

**Issue by sonygod** [R32/flash.Memory#7]
in this example,I use array to store the pre ptr,but I don't think it's perfect  to use.

     package;

    import haxe.io.Bytes;
    import mem.Alloc;
    import Mem;
    import mem.Ptr;

    @:build(mem.Struct.build()) abstract FlexibleStruct(Ptr) {
        @idx(4, 0) var length:Int;
        @idx(2, 4) var flag1:Int;
        @idx(2, 6) var flag2:Int;
        @idx(2, 8) var flag3:Int;
        @idx(2, 10) var flag4:Int;
        @idx(2, 12) var flag5:Int;
        @idx(2, 14) var flag6:Int;

        public inline function toInt():Int
            return cast this;
    }

    class Main {
        public static function main() {
            Mem.init();

            var arr:Array<Int> = [];

            var x = new FlexibleStruct();
            arr.push(x.toInt());
            x.length = 100000;

            x.flag2 = 128;

            var x = new FlexibleStruct();
            arr.push(x.toInt());
            x.length = 10123;

            x.flag2 = 123;

            var x = new FlexibleStruct();
            arr.push(x.toInt());
            x.length = 101233;

            x.flag2 = 124;

            var t:FlexibleStruct = cast new Ptr(arr[0]);

            trace(t.flag2);
        }
    }

**Comment by R32** [comment]
什么?  你的意思是给字段添加一个 next/prev 的链表字段? 

(这个是练习用的, 最好不要用在项目上)

**Comment by sonygod** [comment]
OK .

**Comment by R32** [comment]
你要是能上QQ的话, 这有个haxe群 30373020, 里边还是有2,3个人说话的.(我不是群主)
